<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>itbXlib</RootNamespace>
        <PackageId>itbXLib</PackageId>
        <Authors>x341dev</Authors>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Company>ITecBCN</Company>
        <Description>A helper library for activities for the Institut Tecnològic de Barcelona</Description>
        <RepositoryUrl>https://github.com/x341dev/itbXLib</RepositoryUrl>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MongoDB.Driver" Version="3.8.0" />
    </ItemGroup>

</Project>
