<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>itbXlib</RootNamespace>
        <PackageId>itbXLib</PackageId>
        <Authors>x341dev</Authors>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Company>ITecBCN</Company>
        <Description>A helper library for activities for the Institut Tecnològic de Barcelona</Description>
        <RepositoryUrl>https://github.com/x341dev/itbXLib</RepositoryUrl>
    </PropertyGroup>

</Project>
