name: Auto Release & Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: false

      - name: Mostrar versión calculada
        run: echo "La nueva versión será ${{ steps.version.outputs.version }}"

      - name: Configurar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Build & Pack
        run: |
          dotnet build --configuration Release --no-restore
          dotnet pack --configuration Release --no-build -o ./dist /p:Version=${{ steps.version.outputs.version }}

      - name: Publicar en NuGet
        env:
          SECRET: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./dist/*.nupkg --api-key $SECRET --source https://api.nuget.org/v3/index.json

      - name: Crear GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          body: "Automated release based on commits."
          generate_release_notes: true
          files: ./dist/*.nupkg