name: .NET Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar (Build)
        run: dotnet build --no-restore

      - name: Ejecutar Tests
        run: dotnet test --no-build --verbosity normal